### ISSUE TITLE
Multithread

### ISSUE THREAD

**Issue by ufkundou** [Hattorius/discord-account-generator#1]
I'm getting problems when trying to implement multihread with proxy.

**Comment by ufkundou** [comment]
Traceback (most recent call last):
  File "c:\Users\Ufkun Doğu TUTKAK\Desktop\discord-account-generator-main\main.py", line 13, in createAccount
    session = create(capthaAPI=anticaptcha,
TypeError: 'int' object is not callable

**Comment by ufkundou** [comment]
Traceback (most recent call last):
  File "c:\Users\discord-account-generator-main\main.py", line 13, in createAccount
    session = create(capthaAPI=anticaptcha,
TypeError: 'int' object is not callable

**Comment by Hattorius** [comment]
Was an error on my side with creating the examples. View the new example in the readme.
https://github.com/Hattorius/discord-account-generator/commit/e815a376d5a2459f2bad56068426136145660635
