### ISSUE TITLE
Error when checking request token

### ISSUE THREAD

**Issue by invictusro** [Hattorius/discord-account-generator#19]
```
Discord session created
Waiting for captcha
Sending register request
{'captcha_key': ['sitekey-secret-mismatch'], 'captcha_sitekey': 'xxxxxxxxxxxxxxx', 'captcha_service': 'hcaptcha'}
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\discordTokens\generator.py", line 25, in <module>
    createAccount()
  File "C:\Users\Administrator\Desktop\discordTokens\generator.py", line 15, in createAccount
    session = create(capthaAPI=anticaptcha,
  File "C:\Users\Administrator\Desktop\discordTokens\creator\__init__.py", line 34, in create
    session.register(captchaKey, dob, accountEmail.email, password, username)
  File "C:\Users\Administrator\Desktop\discordTokens\creator\discord.py", line 109, in register
    self.token = response['token']
KeyError: 'token'
```
Hi guys, any clue why this is happening ? Was this patched ?

**Comment by bickkysahani** [comment]
i am also facing the same issue.

**Comment by HuseynG** [comment]
Hi, I want to try the code ass well. What do you suggest?

**Comment by HuseynG** [comment]
I have also tried to use the sms activate manually to verify discord aaccount with number, with actual email. And it got banned straight away.
